### ISSUE TITLE
[QUESTION] About metachain/shardchain relationship

### ISSUE THREAD

**Issue by zhiqiangxu** [ElrondNetwork/elrond-go#2727] opened 2021-01-19 13:48 UTC
After code and white paper reading, I know that elrond works by dividing time into fixed `epoch` and `round`, at the beginning of each epoch, all eligible validators for all shardchains and the metachain are chosen based on the state(as observed by metachain, to be explicit) at the end of last epoch, which are further divided into each shardchain and metachain based on a deterministic algorithm.

My doubt is, when can a shard block be considered finalized? Is it a MUST that the shard block be notarized on metachain to be considered finalized? Under extreme conditions, it can happen that there's a big gap between the shard chain nonce notarized by metachain and the actual nonce consensused within the shardchain.

Another doubt is when reading code, I find that shardchain epoch start block depends on metachain epoch start block, so it means at the start of epoch start, the shardchain will **wait** for the epoch start block of metachain, is this correct?

**Comment by AdoAdoAdo** [comment] 2021-01-19 18:37
Yes a shard block is considered finalized if it is notarized on metachain, and the respective metachain block needs to be confirmed, this is currently a must.

The gaps in nonce are not so important here. There can be missed blocks in metachain or in shards (e.g due to offline block proposers).
On shards, we have a smaller consensus (63) so it is more important here to also have one (shard) block confirmation before metachain notarizes it. In this case if for example we end up in shard with multiple successive offline block producers, it may take longer to get the block notarized in metachain, as it requires the internal shard confirmation.

The epoch start is triggered by metachain, and shards need to follow that as we have certain events happening with an epoch start that are effective for the entire network in the following epoch. One of those as you mentioned is the shuffling of nodes between shards, which is computed by metachain nodes. The shard chains will not advance to the next epoch without metachain advancing first, as the start of epoch block created by the metachain shard is also the change of epoch trigger for the shards.

**Comment by zhiqiangxu** [comment] 2021-01-20 00:42
Thanks, this clarifies a lot of things!

It appears that the metachain/shardchain relationship has much to do with `ComputeLongestChain`(`ComputeLongestMetaChainFromLastNotarized` and `ComputeLongestShardsChainsFromLastNotarized` both depends on that), can you elaborate on the design of this part?

**Comment by AdoAdoAdo** [comment] 2021-01-20 09:44
Indeed ComputeLongesChain... functions deal with deciding the canonical chain. Some functions make use also of the relationship with the metachain, so they enforce that the shard canonical chain includes the latest shard block notarized by metachain. So in short, for shard, it should return the longest valid chain, that includes the latest shard block notarized by metachain. For metachain it should return the longest valid chain.
 
For your second question, the shard node decision will be something like following:
1. If Metachain has notarized a block that is not on my (shard) previously followed canonical chain, then I need to rollback the blocks up to the last block that matches what metachain has notarized for my shard, then follow the newly computed canonical chain (that will include the new shard block notaried by metachain). 
2. If Metachain notarization does not change my computed canonical chain, then keep following the shard chain. In this case, if 
  a. Metachain does not notarize any new block from shard chain, I continue to add blocks on same chain, although the last final (non revertible block) shard block is still the last metachain notarized block, and all the created blocks on top might be reverted.
  b. Metachain notarizes another block on my previously computed canonical chain so the canonical shard chain remains the same, and the last final shard block advances to the newly notarized shard block. 

Metachain may still continue to notarize shard blocks from previous epoch, as long as the consensus round "stamped" on the shard blocks is still below the (metachain start of epoch block round + grace period). All newer shard blocks (with a round larger than start of epoch block round + grace period) need to have new epoch, or they won't be accepted by metachain.

**Comment by zhiqiangxu** [comment] 2021-01-20 10:04
Here is a special edge case for the longest chain:

If the shard nonce is `91` while the notarized nonce for this nonce is `90`, after epoch change, in the 1st round, leader of this shard was not in the shard in the previous epoch, so it will propose block `91` based on notarized block `90`.Then in the 2nd round, the leader was also in the previous epoch, so it will have two block `91`, one from this epoch, one from the previous epoch,  how will it decide the longest chain in this case?

**Comment by AdoAdoAdo** [comment] 2021-01-20 12:03
One of the blocks will be invalid, as it is produced by the wrong validators (every validator verifies the BLS aggregated block signature with respect to the correct nodes configuration of the epoch). 

All leaders that produce blocks *WERE* in this shard in previous epoch, either as eligible or in the waiting list of the shard (we use waiting lists as buffering in order for all eligible nodes to be synchronized when they need to produce blocks). 

Node shuffling process works like this:
1. Remove nodes from each shard eligible list (as long as there are enough nodes in the shard waiting list to replace them and not more than the shuffling rate)
2. Replace them with the nodes from waiting lists
3. Shuffle the removed nodes from step 1 and distribute them to waiting lists.

Metachain will only notarize a block if it is produced by a valid consensus group (nodes selected with the correct randomness from the right epoch configuration). The same validation is done by the shards. Since metachain is the first to enter the new epoch and decides the configuration of nodes, it may be the first to see that a block is not produced by the right consensus group, and will only notarize the valid nonce 91 block header. Shard nodes will follow the metachain notarization, on their canonical chain.

**Comment by zhiqiangxu** [comment] 2021-01-20 12:44
So after epoch change, the shard blocks that fails to be notarized in time by the last metachain block of the last epoch, will become invalid blocks?

I was thinking that some old validators(that stays in both epochs) may relay blocks of previous epoch...

**Comment by AdoAdoAdo** [comment] 2021-01-20 14:47
One other thing to mention is that the first block with changed epoch in the shard is also produced by old epoch nodes (we have a plan to switch to first block in epoch being produced by new nodes but this is not yet implemented). In the current implementation, the effective change of nodes for shards will only happen after the first block with new epoch is produced in shard as well, so the shard epoch effectively becomes E+1 only after this new block is produced. This means that metachain will also take care to validate the first block in the new epoch with the old nodes config.

Also, as all the new eligible nodes were in the same shard in previous epoch as well (either eligible or waiting), they will switch to the new epoch nodes configuration after the shard first block in new epoch is produced. There is a constraint at the protocol level, both for block producer and as well for consensus validators, that if the validators have seen the trigger, the new epoch block needs to be produced, or the validators will not sign it.

The producer for a new epoch in the shard block (not the first new epoch block) was definitely in previous epoch in the same shard, the only options are that he was either:
a. eligible for consensus in the shard
b. waiting to become eligible for consensus, in the same shard, but still synchronizing the shard blocks.

So considering the above, a new node (coming from waiting list of the same shard) can only create earliest a (E+1, R+3, N+2) only if it is linked to a previous block (E+1, R+2, N+1) that has invalidated the (E, R, N+1)  (R+3 because the confirmation was in round R+1 and as mentioned the first new epoch shard block needs to be produced by a previous epoch nodes consensus).

So a fork choice between blocks with different epochs, different rounds, and same nonce, as long as both are valid (still in grace period, produced by the previous epoch nodes, linked to valid previous block in the shard) will choose the block with smaller round in shard. If we are talking about metachain, then it will only notarize a shard block if that one also has a confirmation. I am trying to think if there is any scenario where we can have two valid shard blocks, both with confirmation, with different epochs, and in grace period, the probability would be very small, but in the case of such conflicting blocks the winner would always be the one with the smaller round (as before, blocks need to be valid from all other perspectives).

**Comment by zhiqiangxu** [comment] 2021-01-21 05:43
Wow, that's a lot of info! I think I need to investigate more ..

I was also investigating how shard consensus group size is decided, it appears it's from `NodesSetup.GetShardConsensusGroupSize()`, it's fixed since bootstrap? Am I finding the wrong place?  

I think the shard consensus process is like this: meta epoch block decides all eligible nodes, then in each round, `|consensusSize|` of all eligible nodes for this shard is chosen, and for confirmation, `2*|consensusSize|/3+1` of them needs to sign, it this correct?

**Comment by AdoAdoAdo** [comment] 2021-01-21 11:29
The consensus group size is indeed fixed since bootstrap.

For the metachain we have all eligible validators from the shard in consensus every round, though in different order, so 400 validators.

For the regular shards, we have 63 consensus group size (this is why in shard is important to have one extra confirmation block) before metachain notarizes a block. For two consecutive malicious consensuses we have considered the hypergeometric probability distribution, starting with the assumption that 25% of the network are malicious and on a shard level we have a maximum of 33% malicious validators.

Right, in shard, for each round we have a new randomly sampled consensus group of size 63 validators from the 400 eligible in the shard. Out of those, in order to add a block to the shard blockchain we need at least 2*63/3+1 signatures. For metachain we need at least 2*400/3+1 signatures.

There is a fallback scenario for metachain, to add some tolerance in case too many nodes are offline for extended time, consensus size drops to 201 and only for the proposal of an emergency start of epoch block that would also shuffle the nodes.

**Comment by zhiqiangxu** [comment] 2021-01-22 03:49
`So a fork choice between blocks with different epochs, different rounds, and same nonce, as long as both are valid (still in grace period, produced by the previous epoch nodes, linked to valid previous block in the shard) will choose the block with smaller round in shard. If we are talking about metachain, then it will only notarize a shard block if that one also has a confirmation. I am trying to think if there is any scenario where we can have two valid shard blocks, both with confirmation, with different epochs, and in grace period, the probability would be very small, but in the case of such conflicting blocks the winner would always be the one with the smaller round (as before, blocks need to be valid from all other perspectives).`

I'm also trying to think about this case, still need more consideration.

You mentioned that for shard epoch start block, it's proposed by previous epoch nodes, what about the meta epoch start block? Through code reading, it appears meta epoch start block is proposed by current epoch nodes calculated by the staking contract on metachain.

About the shard malicious  possibility, I calculated this way:

400 nodes, 1/3 are malicious, means 133 malicious and 267 honest. So the possibility is `(Choose_43_from_133*Choose_20_from_267+Choose_44_from_133*Choose_19_from_267+...)/Choose_63_from_400`

the result is exactly `5.386892969171812e-10`!

The code to calculate the above result is here:

```
package main

import (
	"fmt"
	"math/big"
)

func C(n, r int) *big.Float {
	result := big.NewFloat(1)
	for i := n; i > r; i-- {
		result = result.Mul(result, big.NewFloat(float64(i)))
	}

	for i := n - r; i > 1; i-- {
		result = result.Quo(result, big.NewFloat(float64(i)))
	}
	return result
}

func calc() *big.Float {
	nominator := big.NewFloat(0)
	for i := 43; i <= 63; i++ {
		first := C(133, i)
		second := C(267, 63-i)
		nominator = nominator.Add(nominator, big.NewFloat(1).Mul(first, second))
	}
	denominator := C(400, 63)

	return nominator.Quo(nominator, denominator)
}

func main() {
	fmt.Println(calc())
}
```

**Comment by AdoAdoAdo** [comment] 2021-01-22 10:21
In metachain currently we have the same mechanism for who proposes the start of epoch block for epoch e+1, it is still the nodes from epoch e.

The only difference for metachain is that in case of multiple offline nodes we have a fallback mechanism where an "emergency" start of epoch block can be produced by a smaller consensus.

**Comment by zhiqiangxu** [comment] 2021-01-24 14:07
What will happen in this edge case:

```
       ----- A ------ C
D
        ---- B 
```

On metachain, the leader for **current** round collected enough signatures and committed the block `C`, so it will finalize the **previous** block `A` (with a fork block `B`), but accidently the block `C` doesn't reach other validators, and the other validators finally agreed on block `B`. But the current leader doesn't know that, and it will not sign on any block that doesn't link to the "finalized" block `A`, is there any mechanism for this `leader` to recover  in this case?

**Comment by AdoAdoAdo** [comment] 2021-07-05 09:58
As far as I remember the discussion continued on telegram, with multiple other topics.
Answering the previous question below and closing the issue:

In case block C was not accepted by the network (e.g problem with final block info propagation), and instead block B got accepted by the network, there is a rollback mechanism where the block C proposer/leader continuously rolls back the non canonical blocks and then continues synchronizing on the canonical chain.

**Closed by AdoAdoAdo** 2021-07-05 09:58 UTC
