### ISSUE TITLE
v1.0.19 - shard 0 - constant cpu 100% - logs attached

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#505] opened 2019-10-02 07:32 UTC
![image](https://user-images.githubusercontent.com/16723548/66025694-c1291800-e4ff-11e9-8c78-fd8ad683fbd5.png)

[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3679934/logs.zip)

**Comment by drdelphi** [comment] 2019-10-02 07:34
[logs.zip](https://github.com/ElrondNetwork/elrond-go/files/3679941/logs.zip)

**Comment by iulianpascalau** [comment] 2019-12-03 08:18
This was caused by a bad config. Fixed as of today, 2019.12.03

**Closed by iulianpascalau** 2019-12-03 08:18 UTC
