### ISSUE TITLE
[BUG] Cannot stake 10 nodes at a time with erdpy v1.0.118

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1820] opened 2020-05-28 23:11 UTC
I'm staking nodes with erdpy, staking up to 9 at a time works fine, tx gets executed, but when I've tried with 10 it didn't execute:

Input data : 
`stake@0a@eb01a48c18b930d640b4e8cc2ff6c5ec8bf3941d4c04d6f1fbb685bc9c6e09282145853a61d539f232e003a2a920ee073d7914d1c6540fbc891d9c8386a4454bebb61e10a9df4056821a82fca86081c81b422f66d2a753c8fc23ca5ba3fecf84@67656e65736973@eb01a49153d1708b9fcce308c18d3281eebdecf987ad206124f3be5c82224af62abe50084dd3c2bca64e587e472ff418c29c827893ac99f4e72129e3f43ce9b8e8c5d63d715dcd949e9d41dafe2ab28c1fac37e2a41234ca4617f130ed6f6b82@67656e65736973@eb01a49dbea3cb627df13626818d11d5ccb708ba3ea93bd202f529c3b5cb6583f268feb7d6dd5e17b8416cc7ca864a0c4957f76a6c7267b69f4c0a2e6fe1701481f5f25fded189ea6bd2c125ed21d3f55bd95d84951881c780409aba900ada12@67656e65736973@eb01a4a72306282918ea8bcdfd2f8ec293d005607cbe3f221322cebb08447577ad832e6f68dcb2c8a98a06fa22267707ec4e47ead44aa096f5fc302a51929376ff51dcd3d84b189f59688e89166dfe2a73896f45b495dd7058fcfe87b09abf8b@67656e65736973@eb01a4abd83f7691da4caa0d40ecb247d31ff0b910b1a0c333f45b5d8af7ae1610ca3a30c62c3ba25ec45f477b1510089ffc68f6c24360a9654b5c7d0ebba8bbda9e0812b9b46c2ade729a954b7977138a0de88df72366213eb47f4178749d09@67656e65736973@eb01a4b5d0072e98116a4321aecdd2c0ca39180bb5ce9354debd9bc2c6827d4b6904d0b98955f58be98aa79190a2840b7df11e97a1a50dbc210469d612dd98e907c78068142d243a66b0bcaedd08b8b6d29a643747ffe922c010437edcda3b0e@67656e65736973@eb01a4ba003929b00f0631ed02275f537ca683a891f54dd0fce94fc2525990893d26c229be202940d7cff1267093f7094139d05ef3ca205decf6684163598359a83f3d5592146ec972c30b86d511218062b9af3e4e5e39b4d03eb29e52837f82@67656e65736973@eb01a4bd250d06301bc51edf3e3e35f464a4cf4f1ea8d1be433ef36c25408aab5523d529d4034487c959b75f66b4db0062c3173b8f5ac1704485ff44552857ff6b11218b3d234e235c173fc65148e27d39f45ccbbc2ba7eefd98ee6ecda18506@67656e65736973@eb01a4c120ffc2ff43e71a4776f65470c504ff4f3d3e19fa7908e02941cf71e89f4ed628b79d4865c5fba3b865028e11428586f5af9f75e61378d0e15d6b489aa487ceb1e94a5a89676d716b0be535617f69dd3c84bb0a99f4cb10ef84ac4383@67656e65736973@eb01a4d121599993dc8fecaf6b4ff48ebeb2f552e70edb9fa6072700ae48222b2d9c7032ced766c805f2a499e89bd1122f8d279b9f791391d7fe8549f1f95b3325562eff9cc544029e8e9213bf22ea7f01501900f17cf7cdd5025ae1d98fc395@67656e65736973`

https://explorer.elrond.com/transactions/81ae5e7b1f7e7f1570ec98f5a73b6a365e8646ae43ccad960873e8ef2b51d83f

![image](https://user-images.githubusercontent.com/16723548/83203148-77a5d100-a151-11ea-82fe-43633b39cced.png)

Next try with 9 nodes worked just fine:

![image](https://user-images.githubusercontent.com/16723548/83203219-9e640780-a151-11ea-8bde-58c0bdba3e93.png)

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.118-0-ga20faf818/go1.13.1/linux-amd64
</pre>
</details>

**Comment by miiu96** [comment] 2020-05-29 10:42
Hello. Thank you for the feedback I will try to reproduce this bug and fix the problem.

**Comment by sasurobert** [comment] 2020-05-29 10:54
This is not a bug. You see for 9 staked keys you used 47.870.000 GAS. For 10 staked keys you would need 53.000.000GAS at least.

**Comment by soringp** [comment] 2020-05-29 10:56
@sasurobert erdpy does the gas calculation, so for some reason for 10 it didn't calculate the right amount

**Comment by iulianpascalau** [comment] 2020-06-01 09:00
We should get erd-py fixed than.

**Comment by iulianpascalau** [comment] 2020-07-30 14:41
should be fixed as of today v1.1.0

**Closed by iulianpascalau** 2020-07-30 14:41 UTC
Labels: bug
