### ISSUE TITLE
fork inducing duplicate nodes - revert failing - shard 3 dead v1.0.109

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1460] opened 2020-04-22 21:50 UTC
fork detected  nonce = 13327 hash = 0ee87c..ac31a7

![image](https://user-images.githubusercontent.com/16723548/80209619-0f883a80-863b-11ea-8793-85df1d8880f1.png)

Here are my two guilty nodes running with the same key, one in the US, one in RO.

![image](https://user-images.githubusercontent.com/16723548/80041630-9804bf00-8505-11ea-8f8f-733a5eda5bfd.png)

It looks like they've killed Shard 3:

![image](https://user-images.githubusercontent.com/16723548/80042005-97b8f380-8506-11ea-8fa8-bfaeaecfe12d.png)

@LucianMincu here are the standard node logs, hope there's enough, I can save the db if needed.

[zero.s3u.logs.zip](https://github.com/ElrondNetwork/elrond-go/files/4519152/zero.s3u.logs.zip)
[zero.s1.logs.zip](https://github.com/ElrondNetwork/elrond-go/files/4519153/zero.s1.logs.zip)

**Comment by soringp** [comment] 2020-04-22 22:10
Not my finding but here are some details from TG:

error = trie recreate error: hash not found, for root efb979df6a035aae0f105bb4ae67b0c5fa2763caed3a901434804aef1a5a0760

DEBUG[2020-04-22 20:06:00.636]  received shard header from network in block tracker shard = 3 epoch = 23 round = 13860 nonce = 13327 hash = 259ccb..100e80

DEBUG[2020-04-22 20:06:00.934]  received shard header from network in block tracker shard = 3 epoch = 23 round = 13860 nonce = 13327 hash = 0ee87c..ac31a7

**Comment by soringp** [comment] 2020-04-23 07:14
![image](https://user-images.githubusercontent.com/16723548/80070119-22234680-854b-11ea-82d1-301c6bd1e9d0.png)

Dead alright!

**Comment by flyingbasalt** [comment] 2020-04-23 09:33
What proves that the cause was your duplicated nodes?

**Comment by soringp** [comment] 2020-04-23 09:47
The strongest evidence comes from Lucian, with same block proposed twice:

2020-04-22 20:06:00.636 .. received .. nonce = 13327 hash = 259ccb..100e80
2020-04-22 20:06:00.934 .. received .. nonce = 13327 hash = 0ee87c..ac31a7

Unfortunately my logging is set to Info, not Debug, so I cannot link 0ee87c to the duplicate.

**Comment by flyingbasalt** [comment] 2020-04-23 13:57
You're right that sounds quite convincing. The good thing is that you and some others like me running several duplicated nodes made this unusual situation crop up. 
I still think that once the fix for this issue is in place, #1354 remains a great idea.

**Comment by soringp** [comment] 2020-05-04 13:33
**Lucian's TG explanation for this bug:**

The trie snapshot and trie pruning for a certain root hash needed to be executed in this order. There was an edge case when the pruning occurred before the snapshot, the result being that the hashes needed for the snapshot were removed before they were saved in the snapshot, thus the error.

**Comment by elrondscammer1** [comment] 2020-05-09 08:33
BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump fuck fuck fuck

**Comment by elrondscam6** [comment] 2020-05-09 14:53
ERD Scam Coin. Team ERD is a con man. Don't buy ERD. I send this message every day to everyone in the group. Prevent more people from being conned by sharing with you.

**Comment by elronscam8** [comment] 2020-05-09 15:03
BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ERD
  We want our money back, Romanian sons of bitches.

**Comment by iulianpascalau** [comment] 2020-05-18 08:00
Great find, thanks! The shard got stuck because of a trie error that was caused by the double signing. Should be fixed by now.

**Closed by iulianpascalau** 2020-05-18 08:00 UTC
Labels: needs investigation
