### ISSUE TITLE
Transaction with unicode characters as data doesn't get recorded or is not displayed (1.0.38 blockchain)

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#636] opened 2019-11-06 17:05 UTC
I've tried sending a transaction with a regular 'abcdef' text as data, from e87669dde6301682fe56efea1a222cad690537248a3db474770a4d82b8c772d0 to 
b96bb87913469147272ddceb69dfb6041817ea9e0c6b16558bc25b1b57f5432a and it worked. 

Transaction id: 
https://testnet.elrond.com/#/tx/fafaf435b93994a08b806c47f5a5f19b5d6432fafd63f8a050bbf13204407bc5

The failed attempt happens when the data field contains: 'ʰ˥˽əṪɏȭƢ𑙠𑙠‡'
This value can be set correctly as a node name:

![image](https://user-images.githubusercontent.com/16723548/68320199-315f2680-00c8-11ea-9ad2-907baba8b052.png)

This is the failed transaction, not visible on explorer or elastic search:

https://testnet.elrond.com/#/tx/c70fc9d3b7dc69a88d5519e840034f0b9fe522386665b92ae3ae42d749277dde

https://elastic-aws.elrond.com/transactions/_doc/c70fc9d3b7dc69a88d5519e840034f0b9fe522386665b92ae3ae42d749277dde

**Comment by truecryptoleo** [comment] 2019-11-06 20:06
the same problem... I've tried sending a transaction with a regular 'чакра' and '@#zadж' text as data, from 3db669fdb04a8d072ddbfc54e5cc9e99b5dbbc0a14db657ddb230b92d055d0c8 to b96bb87913469147272ddceb69dfb6041817ea9e0c6b16558bc25b1b57f5432a 
that tx not visible on explorer...
ERD can be found on the balance
![image](https://user-images.githubusercontent.com/50778660/68333303-dd296600-010a-11ea-86cb-ca548c622fea.png)
but i can't send them
![image](https://user-images.githubusercontent.com/50778660/68333658-853f2f00-010b-11ea-9bfe-25de344577fc.png)

**Comment by bogdan-rosianu** [comment] 2019-11-07 15:35
Hello. We are aware about this issue and the fix is in testing process. The issue is that javascript and golang have different approaches when they marshal a structure which contain special characters and we had to use something that performs the same in both of them (and others too).

**Comment by iulianpascalau** [comment] 2020-05-14 06:21
Fixed, reference PR: #1513

**Closed by iulianpascalau** 2020-05-14 06:21 UTC
Labels: P2
