### ISSUE TITLE
[Transaction-Hash] Offline Transaction Hash generation

### ISSUE THREAD

**Issue by atulrupnar** [ElrondNetwork/elrond-go#2283] opened 2020-09-09 04:57 UTC
At the moment, there is no way to generate transaction hash offline. The only way to get txhash is upon the broadcast of the transaction, it returns txHash. 

The utility is already there. Just need to open endpoint or provide way to create txHash offline. so it will be easy for integrators to keep a track of unsigned transactoins.

**Comment by andreibancioiu** [comment] 2020-09-09 21:51
For this feature, I see two possible options:

1) on the Node (Observer) or Proxy, implement an endpoint `POST /transaction/hash` which would receive the whole transaction (signed), compute its hash (blake2b) and return it as a result.

2) in the SDK (erdpy and erdjs), offer utility functions to compute the hash of a prepared (and signed) transaction.

On the long term, we should implement both.

On the short term, would you prefer the second option, though?

**Comment by atulr-crypto** [comment] 2020-09-14 09:18
Sure, I would prefer the second option to compute hash completely offline.

**Comment by khaq** [comment] 2020-09-22 05:35
I use try to produce tx hash in go (master) but it does not match the API returned hash. The transaction was broadcasted on mainnet

API: `0584ef98601ed1fb65e689dfbc5bf4f132f4128f2b0c396e34022fb5c0d092e9`
Go: `12281a1e7891e613b401d60e5e8318f84ed89c249bcd5fd4d7ed41af7c21efe1`

```go
package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/big"

	"github.com/ElrondNetwork/elrond-go/core/pubkeyConverter"
	"github.com/ElrondNetwork/elrond-go/data/transaction"
	"github.com/ElrondNetwork/elrond-go/hashing/blake2b"
)

func main() {
	valAsBigInt, _ := big.NewInt(0).SetString("100000000000000", 10)
	converter, _ := pubkeyConverter.NewBech32PubkeyConverter(32)
	receiverAddress, _ := converter.Decode("erd1lp8twnudtuf3tsal427ye3t7r9s6tsy74tchj5895kcyx936cl4q22k284")
	senderAddress, _ := converter.Decode("erd1elrprmjd7epnwc2cv6ex9af7qnwc9g86r38l73waej84twfcrl3su32vcp")
	signatureBytes, _ := hex.DecodeString("98854aad90ebf1a71975b27fba8f0ecf2c477d49f4b9b378722a3c01e56837fd52ab0f5faea98e97fb130f85150f2399339f51eb5fd0164f572918f542402304")

	tx := &transaction.Transaction{
		Nonce:     uint64(0),
		Value:     valAsBigInt,
		RcvAddr:   receiverAddress,
		SndAddr:   senderAddress,
		GasPrice:  uint64(1000000000),
		GasLimit:  uint64(50000),
		Data:      nil,
		Signature: signatureBytes,
		ChainID:   []byte("1"),
		Version:   uint32(1),
	}

	bytesBuffer := new(bytes.Buffer)
	jsonEncoder := json.NewEncoder(bytesBuffer)
	jsonEncoder.SetEscapeHTML(false)
	jsonEncoder.Encode(tx)

	encodedResult := trimLineFeed(bytesBuffer.Bytes())

	fmt.Println(string(encodedResult))

	hasher := blake2b.Blake2b{}

	fmt.Println(hex.EncodeToString((hasher.Compute(string(encodedResult)))))
}

func trimLineFeed(bytes []byte) []byte {
	// this should be replaced, but for some reason, bytes.TrimRight(b, "\r") does not work
	lastByte := bytes[len(bytes)-1:]
	if lastByte[0] == byte(10) { // hardcoded for now
		return bytes[:len(bytes)-1]
	}

	return bytes
}
```

**Comment by bogdan-rosianu** [comment] 2020-09-22 07:43
Hi, @khaq 
For the `transaction` object, please use it's function `GetDataForSigning` that receives 2 params: an encoder (in this case a `bech32` encoder and a marshalizer which will be json). That function will convert all the field to the desired signing format (sender and receiver in bech 32 string, chain ID also string and so on)
So something like: 
```
jsonMarshalizer := &marshal.JsonMarshalizer{}
encodedResult, err := tx.GetDataForSigning(converter, jsonMarshalizer)
```

**Comment by bogdan-rosianu** [comment] 2020-09-22 07:52
Hi @khaq !
Please use the `CalculateHash` function from the `core` package and also use out protobuf instead of json
Example:
```GOLANG
internalMarshalizer := &marshal.GogoProtoMarshalizer{}
hasher := &blake2b.Blake2b{}
txHash, _ = core.CalculateHash(internalMarshalizer, hasher, tx)
fmt.Println(hex.EncodeToString(txHash))
```

**Comment by khaq** [comment] 2020-09-22 07:56
Thank you @bogdan-rosianu. It works for me.

**Comment by bogdan-rosianu** [comment] 2020-09-22 08:08
@atulrupnar 
you can use the `/transaction/simulate` endpoint which receives the same request as the `/transaction/send` endpoint and it will also output the execution simulation so you will know if the transaction will be correctly executed or not.

**Comment by khaq** [comment] 2020-09-22 08:16
Hi @andreibancioiu. It've just tried `/transaction/simulate` but it seems not be documented and the public `https://api.elrond.com/transaction/simulate` returns `Missing Authentication Token`?

**Comment by bogdan-rosianu** [comment] 2020-09-22 08:18
Hi. We will document it, thanks for the notice. And yes, it is not enabled on the public API yet. If you have a local running testnet or send that request to your node/observer on mainnet/testnet, you can use it.

**Comment by atulrupnar** [comment] 2020-10-28 10:50
i just tested the /simulate api. its not working. The following is the
error response:
{
    "data": null,
    "error": "sending request error",
    "code": "internal_issue"
}

**Comment by bogdan-rosianu** [comment] 2020-10-28 10:53
Hello. this could be a proxy issue because it's observers are down

**Comment by atulrupnar** [comment] 2020-10-28 11:13
Hi, we are running own node setup and everything seems fine. we are not
trying the /simulate endpoint on public api

**Comment by bogdan-rosianu** [comment] 2020-10-28 11:16
Hello. Yes, the described error appears when there are issues with the observers. Can you put the output of a different endpoint? for example `GET` - `proxyAddress/network/status` ?

**Comment by atulrupnar** [comment] 2020-10-28 11:21
the following is example status for shard id 1.

{
    "data": {
        "status": {
            "erd_current_round": 1294402,
            "erd_epoch_number": 89,
            "erd_nonce": 1294262,
            "erd_nonce_at_epoch_start": 1281552,
            "erd_nonces_passed_in_current_epoch": 12710,
            "erd_round_at_epoch_start": 1281691,
            "erd_rounds_passed_in_current_epoch": 12711,
            "erd_rounds_per_epoch": 14400
        }
    },
    "error": "",
    "code": "successful"
}

**Comment by atulrupnar** [comment] 2020-10-28 11:31
is there any offline code I can copy and generate txhash offline??

also are there any recent changes in the txhash generation function. I have
created offline txhash generation by referring go code but somehow its not
working for 1 of the txhash (maybe more, i came across  1 only). so
wondering whats wrong.

**Comment by bogdan-rosianu** [comment] 2020-10-28 11:44
sure. you can use the following code (adapted from the original question). you can extract it to a function or soemthing else:

``` golang
package main

import (
	"encoding/hex"
	"fmt"
	"math/big"

	"github.com/ElrondNetwork/elrond-go/core"
	"github.com/ElrondNetwork/elrond-go/core/pubkeyConverter"
	"github.com/ElrondNetwork/elrond-go/data/transaction"
	"github.com/ElrondNetwork/elrond-go/hashing/blake2b"
	"github.com/ElrondNetwork/elrond-go/marshal"
)

func main() {
	valAsBigInt, _ := big.NewInt(0).SetString("100000000000000", 10)
	converter, _ := pubkeyConverter.NewBech32PubkeyConverter(32)
	receiverAddress, _ := converter.Decode("erd1lp8twnudtuf3tsal427ye3t7r9s6tsy74tchj5895kcyx936cl4q22k284")
	senderAddress, _ := converter.Decode("erd1elrprmjd7epnwc2cv6ex9af7qnwc9g86r38l73waej84twfcrl3su32vcp")
	signatureBytes, _ := hex.DecodeString("98854aad90ebf1a71975b27fba8f0ecf2c477d49f4b9b378722a3c01e56837fd52ab0f5faea98e97fb130f85150f2399339f51eb5fd0164f572918f542402304")

	tx := &transaction.Transaction{
		Nonce:     uint64(5),
		Value:     valAsBigInt,
		RcvAddr:   receiverAddress,
		SndAddr:   senderAddress,
		GasPrice:  uint64(1000000000),
		GasLimit:  uint64(50000),
		Data:      nil,
		Signature: signatureBytes,
		ChainID:   []byte("1"),
		Version:   uint32(1),
	}

	internalMarshalizer := &marshal.GogoProtoMarshalizer{}
	hasher := &blake2b.Blake2b{}
	txHash, _ := core.CalculateHash(internalMarshalizer, hasher, tx)
	fmt.Println(hex.EncodeToString(txHash))
}
```

**Comment by atulrupnar** [comment] 2020-10-28 12:46
Thanks @bogdan, can i have same functionality in javascript. not
familiar with golang. I already built function using protobuff and black2b
which works quite well.

**Comment by bogdan-rosianu** [comment] 2020-10-28 13:29
@andreibancioiu can help you with a javascript alternative code

**Comment by andreibancioiu** [comment] 2020-10-29 08:12
@atulrupnar, we'll most probably add the feature in this on-going PR:

https://github.com/ElrondNetwork/elrond-sdk/pull/75

**Comment by atulrupnar** [comment] 2020-10-29 13:45
i found some bugs in bigInt function written in js library. its not
matching the golang bigInt conversion. anyone here to chat. I will give you
more details.

**Comment by AdoAdoAdo** [comment] 2020-10-29 14:01
hi @atulrupnar, is this about protobuf marshal/unmarshal?
there was some plugin we created for gogoproto BigInt conversions which you probably do not have in js

**Comment by AdoAdoAdo** [comment] 2020-10-29 14:24
as @andreibancioiu mentioned, we might add this feature in elrond-sdk (erdjs) but until then, if you want you can take a look at 

https://github.com/ElrondNetwork/elrond-core-js/commit/f266f56518f30271b53bd005fe307067f1dc0734

we just removed this from elrond-core-js but you can see an example for converting to golang bigInt format.

**Comment by atulr-crypto** [comment] 2020-10-29 14:49
actually, I am already using `toErdBigInt` function to pass value before serialisation. but it has a bug. it works perfect for small values (any value with 15 decimals works) but doesn't create same value for very big amount.

**Comment by atulr-crypto** [comment] 2020-10-29 14:51
> hi @atulrupnar, is this about protobuf marshal/unmarshal?
> there was some plugin we created for gogoproto BigInt conversions which you probably do not have in js

protobuff marshal/unmarshal works perfectlly. The issue is passing value/amount in the right format (in golang Math.BigInt is used but js alternative doesn't work for all cases)

**Comment by andreibancioiu** [comment] 2020-12-11 13:14
@atulrupnar, we have implemented the off-line computation of the hash in **erdjs**.
https://github.com/ElrondNetwork/elrond-sdk/blob/master/erdjs/src/transaction.spec.ts#L30

Large numbers (for values) are supported:
https://github.com/ElrondNetwork/elrond-sdk/blob/master/erdjs/src/transaction.spec.ts#L83

The hashes are automatically computed after signing the transaction. **Hashes cannot be computed for not-yet-signed transactions** (since the `signature` field must be present, and it influences the content hash). In order to manually call the hash computation, please see:

https://github.com/ElrondNetwork/elrond-sdk/blob/master/erdjs/src/transaction.ts#L303 

We have also added a series of transaction construction examples in our main repository:

https://github.com/ElrondNetwork/elrond-go/tree/master/examples

Thank you for reporting the issue and for your valuable notes (about _gogo proto_ and the JavaScript _BigInt_) :100: 

We will now close this issue :pray: 

CC: @AdoAdoAdo, @bogdan-rosianu

**Closed by andreibancioiu** 2020-12-11 13:14 UTC
Labels: enhancement
