### ISSUE TITLE
[BUG]Node can't pass block nonce 10270062

### ISSUE THREAD

**Issue by poussette** [ElrondNetwork/elrond-go#4295] opened 2022-07-14 21:44 UTC
Node losing rating, block nonce 10270062.
1- Stopped node 
2- Removed DB
3- Duplicated DB from another waiting node in same shard on same host (this waiting node was stopped before)
4- Restarted node.

Procedure done but same issue.
Retried a second times and it has been successful.

Logs joined
[elrond-node-4-c0db6932b90a.log.gz](https://github.com/ElrondNetwork/elrond-go/files/9115673/elrond-node-4-c0db6932b90a.log.gz)

**Comment by iulianpascalau** [comment] 2022-07-15 09:34
The error signaled when processing the block epoch = 713 shard = 1 round = 10277217 nonce = 10270063 is `receipts hash missmatch`.
This can be caused by a multitude of factors like bad configs, wrong binary version, an internal bug, **wrong/incomplete trie state**
I've emphasized the wrong or incomplete trie state because we have recently found this behavior on our nodes that was related to the closing of the node while it was doing a snapshot. If this occurs on a node with the v1.3.35 version, the snapshot is incomplete but the DB is marked as a DB with a complete snapshot and this might trigger the above error. I can not see from this log, I was wondering if the node started to work just after the epoch 714 was notarized by the metachain. This behavior would have triggered a new trie re-sync from the network. 
This is the PR that contains the fix, it is still under review & heavy testing: https://github.com/ElrondNetwork/elrond-go/pull/4281

**Comment by phanletrunghieu** [comment] 2022-07-18 06:53
[log.txt](https://github.com/ElrondNetwork/elrond-go/files/9129993/log.txt)

There're 2 suspicious log lines

```
error = roll back behind final header is not permitted
error = block bodies does not match
```

**Comment by phanletrunghieu** [comment] 2022-07-18 10:45
This is the log file before node restarted.
https://drive.google.com/file/d/18IhXxEbw49vOycw3DFMB_3BbBeCxxzYA/view?usp=sharing

**Comment by iulianpascalau** [comment] 2022-07-18 13:25
will take a look

**Comment by LucianMincu** [comment] 2022-07-28 19:23
Hi @poussette @phanletrunghieu!

Awesome news for you! 🔥 
elrond-go [v1.3.36](https://github.com/ElrondNetwork/elrond-go/releases/tag/v1.3.36) has been released! 🚀 

The release includes the fixes for the root cause of the issue from above. 

Thanks for reporting it and your contribution! 🙏

**Closed by LucianMincu** 2022-07-28 19:23 UTC
Labels: type:bug
