### ISSUE TITLE
Feature request - uptime in node output

### ISSUE THREAD

**Issue by koen84** [ElrondNetwork/elrond-go#534] opened 2019-10-11 10:12 UTC
I'd like to suggest to print the time a node process has been running in the output, this should make troubleshooting (others) easier.  That way we can tell if someone successfully restarted their node or not.

**Comment by drdelphi** [comment] 2019-10-14 13:21
possible duplicate of #468

**Comment by iulianpascalau** [comment] 2020-05-13 13:50
duplicate with #468. Will be added sometime soon.

**Closed by iulianpascalau** 2020-05-13 13:50 UTC
Labels: enhancement
