### ISSUE TITLE
rating going down after voluntary restart 1.0.95

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-go#1259] opened 2020-03-20 10:00 UTC
I hope it can recover but I've restarted all nodes on a machine where a node was out of sync, and after this restart a good node, in sync, started to have it's rating lower and lower:

![image](https://user-images.githubusercontent.com/16723548/77153352-45695a80-6aa2-11ea-8ce9-9d6e710abacc.png)

3 hours later:

![image](https://user-images.githubusercontent.com/16723548/77153395-62059280-6aa2-11ea-9bf0-0efbd5493a0a.png)

It looks it's going down.

**Comment by soringp** [comment] 2020-03-20 15:02
![image](https://user-images.githubusercontent.com/16723548/77176229-73639480-6acc-11ea-9e16-3a142ab68c9d.png)

![image](https://user-images.githubusercontent.com/16723548/77176333-98580780-6acc-11ea-8ab4-013c1f5813d0.png)

**Comment by flyingbasalt** [comment] 2020-03-20 15:58
Same for my two nodes which started from 99.9 rating and after being offline for 30 minutes still have problems regaining rating more than 7 hours later. It seems a problem with failing as validators, not as leaders. Since a couple of hours one of the two is slowing improving.

```
$ curl -s localhost:8081/validator/statistics | jq '.' | grep -A 7 c41df4b6
    "c41df4b69a2eda6706f7c128680d2ca4cb86a9cf77fe9873307951711b1ebd0e8218cbafc1a4b2a8aadab155754f9a04a4d24028105bdd0e506d18673def4d15b319b14a35a31bf99d219237abe75bbf1ee0933eb7f062b278f8c213a9323409": {
      "nrLeaderSuccess": 10,
      "nrLeaderFailure": 2,
      "nrValidatorSuccess": 206,
      "nrValidatorFailure": 82,
      "rating": 96.946495,
      "tempRating": 97.7163
    },
$ curl -s localhost:8081/validator/statistics | jq '.' | grep -A 7 3c2a08e1
    "3c2a08e121e1deb980617a89e9b139dfa9283008ccd3a88ff8599a64c6db46ea42894e3f9171224a9445dd2655dbf30c08c533452755172e8a7954460ecb0e9ed20f4f211b22d3be34b3faae12871627dd823e9219ce03d20b4b944531de1310": {
      "nrLeaderSuccess": 7,
      "nrLeaderFailure": 0,
      "nrValidatorSuccess": 0,
      "nrValidatorFailure": 308,
      "rating": 93.446,
      "tempRating": 93.1471
    },
```

**Comment by flyingbasalt** [comment] 2020-03-31 11:08
Tested this again today with v1.0.99 on shard 4 which seems to be working fine and the same problem exists.

**Comment by flyingbasalt** [comment] 2020-04-14 13:23
I can't reproduce the problem with v1.0.103. At least not with a brief stop/start which used to be enough to trigger several hours of declining rating.

**Comment by soringp** [comment] 2020-04-14 13:30
rating also goes all the way to 100 now for all active nodes, so there's either a delay or a more generous scoring system in place

**Comment by raduchis** [comment] 2020-05-15 08:25
fixed in https://github.com/ElrondNetwork/elrond-go/commit/8a371048d73511514ef7664e89bf7e57be5162ed

**Closed** 2020-05-15 08:46 UTC
Labels: needs investigation
