### ISSUE TITLE
Installing Elrond node on Raspberry PI Ubuntu 18.4

### ISSUE THREAD

**Issue by supersheepshaker** [ElrondNetwork/elrond-go#1933] opened 2020-06-11 20:58 UTC
I am getting as far as this error after starting Elrond node on my RPI. Any idea why?

~/elrond-utils$ ./termui -address localhost:8080
ERROR[2020-05-27 22:48:29.007]   dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by bogdan-rosianu** [comment] 2020-06-12 07:35
Hello!
This may be caused by many reasons:
1. Does the node process exist in `htop`? Maybe it didn't start for some reason.
2. Did you try again after a while? Maybe you tried to connect to the node a short time after the process starts and termui can't connect yet.
3. Which version of elrond-go do you use? Newer versions' termui app should try again in 10 seconds instead of closing.

**Comment by supersheepshaker** [comment] 2020-06-14 12:17
1. I am attaching my htop screenshot
![image](https://user-images.githubusercontent.com/63821913/84592957-8c6caf00-ae49-11ea-8367-7dfa6a7b8c96.png)

2. I tried for an hour without luck
3. When I run logviewer I see attempt to connect every 10 seconds with the same error
![image](https://user-images.githubusercontent.com/63821913/84592969-99899e00-ae49-11ea-82b2-70db01a715d4.png)

**Comment by iulianpascalau** [comment] 2020-07-23 10:49
The root cause is that the node is not performing as expected because the wasmer library that we use is not (yet) fully functional on ARM processors. We will provide a feedback whenever the library will be fixed by its code owners. Thanks for the feedback.

**Comment by DarthDevOps** [comment] 2021-09-10 07:58
any updates on this?

**Comment by camilbancioiu** [comment] 2021-11-05 15:00
There still is an incompatibility between the Go runtime and the Wasmer dynamic library that only occurs on ARM processors. This week we have tested running the node on a Raspberry Pi and the error was the same: the Go runtime fails with a panic during smart contract execution in Wasmer. This panic completely stops the node.

I'm afraid this is out of our control at the moment, but we're still monitoring the issue ourselves. We do hope to support Raspberry Pi, this is our only blocking issue.

**Closed** 2021-11-05 15:09 UTC
Labels: needs investigation

**Comment by zekdigital** [comment] 2022-08-20 12:37
Any news about this?
