### ISSUE TITLE
validator/statistics route does not return any info

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go#1792] opened 2020-05-22 23:44 UTC
The validator/statistics route of a metachain node does not return any info: 

```
$ curl -s localhost:8081/validator/statistics | jq '.'
{
  "statistics": {}
}
```
same at https://wallet-api.elrond.com/validator/statistics
`{"statistics":{}}`

Is this maybe only starting to work after the first epoch? It is still epoch 0 right now.

<details>
<summary>Executing details</summary>
<pre>
Application version string: v1.0.118-0-ga20faf818/go1.13.5/linux-amd64
Hosting VPS: no VPS 
</details>

**Comment by flyingbasalt** [comment] 2020-05-23 07:55
As an update, now we are in epoch 8 and https://wallet-api.elrond.com/validator/statistics shows information, but `$ curl -s localhost:8081/validator/statistics | jq '.'` still returns empty information.

**Comment by LucianMincu** [comment] 2020-05-25 08:24
![image](https://user-images.githubusercontent.com/30302419/82793842-df1e0100-9e71-11ea-9ef5-9bd9d10f264c.png)

**Comment by citterio** [comment] 2020-05-25 08:48
If it matters, these nodes are started with flags `-use-log-view -rest-api-interface localhost:808n` by script.sh

**Comment by raduchis** [comment] 2020-05-25 15:44
should be fixed in the next release.
Fixed in b93bb4af8ce96da570d9ca842f431db9d9862470

**Comment by iulianpascalau** [comment] 2020-06-01 08:57
Will close for now. Please open a new issue if the problem persists. Thanks.

**Closed by iulianpascalau** 2020-06-01 08:57 UTC
Labels: bug

**Comment by citterio** [comment] 2020-06-04 10:40
Thank you, I confirm the issue is fixed, so my work in progress monitoring tool [vilya](https://pypi.org/project/vilya/) is a good step closer to prime time!

**Comment by flyingbasalt** [comment] 2020-06-04 10:44
Thank you, I confirm the issue is fixed, so my work in progress monitoring tools [vilya ](https://pypi.org/project/vilya/) and [nodeview](https://pypi.org/project/nodeview/) are a good step closer to prime time!
