### ISSUE TITLE
Built binary is failing on Mac os

### ISSUE THREAD

**Issue by harsh-98** [ElrondNetwork/elrond-go#1882] opened 2020-06-08 10:28 UTC
Running below commands fails:
```
./cmd/node/node
```

Error:
```
dyld: Library not loaded: /Users/ccorcov/Projects/elrond/wasmer/target/release/deps/libwasmer_runtime_c_api.dylib
  Referenced from: /Users/harsh.jain/BACKUP/elrond-go/./cmd/node/node
  Reason: image not found
[1]    90720 abort      ./cmd/node/node
```

OS: 
```
Mac version: 10.14.6 (18G3020)
```

**Comment by ccorcoveanu** [comment] 2020-06-10 08:29
You seem to be running an old (backed up `BACKUP`) version of the node binary. How did you build this binary (and when)?

**Comment by harsh-98** [comment] 2020-06-11 11:44
I tried building version v1.0.129 same issue.

**Comment by ccorcoveanu** [comment] 2020-06-11 14:23
Hi again :) Did you follow the build indications in the readme file? https://github.com/ElrondNetwork/elrond-go/blob/master/README.md

I am referring to the arwen build. There is a step where you need to set up your arwen path with: `$ export ARWEN_PATH="$HOME/Arwen/arwen"` then going to elrond-go folder and runnind `$ make arwen`.

Hope this helps!

**Comment by harsh-98** [comment] 2020-06-11 14:39
Just tried still the same.

I tried.
```
./arwen --version
```

Same error:
```
dyld: Library not loaded: /Users/ccorcov/Projects/elrond/wasmer/target/release/deps/libwasmer_runtime_c_api.dylib
  Referenced from: /Users/harsh.jain/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/./arwen
  Reason: image not found
[1]    90546 abort      ./arwen version
```

**Comment by ccorcoveanu** [comment] 2020-06-11 16:45
Can you post the output of `echo $ARWEN_PATH`?
And also of `make arwen`?

**Comment by harsh-98** [comment] 2020-06-11 17:12
```ARWEN_PATH=./cmd/node make arwen```

Output of `make arwen`:

```
# When referencing a non-release version, add the commit hash, like this:
#go get github.com/ElrondNetwork/arwen-wasm-vm/cmd/arwen@...
# When referencing a released version, use this instead:
go get github.com/ElrondNetwork/arwen-wasm-vm/cmd/arwen@v0.3.19
go: finding github.com/ElrondNetwork/arwen-wasm-vm/cmd/arwen v0.3.19
go: finding github.com/ElrondNetwork/arwen-wasm-vm/cmd v0.3.19
go: finding github.com v0.3.19
go: finding github.com/ElrondNetwork v0.3.19
go build -o ./cmd/node github.com/ElrondNetwork/arwen-wasm-vm/cmd/arwen
stat ./cmd/node
16777220 21051441 drwxr-xr-x 8 harsh.jain staff 0 256 "Jun 11 22:40:21 2020" "Jun 11 22:37:37 2020" "Jun 11 22:37:37 2020" "Jun  8 10:02:35 2020" 4096 0 0 ./cmd/node
```

**Comment by ccorcoveanu** [comment] 2020-06-12 10:45
Hello

I dug a bit deeper and I could also reproduce your issue. It seems that there is a combination of small problems in go's linker and the fact that the rust build for wasmer specifies the build path and name where `libwasmer_darwin_amd64.dylib` was originally built. So this is why even though we can load the correct library, it has references to it's original name and path.

Current release versions of arwen still have that `libwasmer_darwin_amd64.dylib`. A temporary solution could be for you to use (https://ide.elrond.com/travis-builds/ARWEN_v0.3.15-120-g03d0b3f_darwin_amd64.tar.gz) this travis build for arwen + the correct lib.

The permanent fix where we bypass the linker issues are on master in arwen and will be available in the next relese.

Please let me know if the binaries in the url help for now and I will be back with an update when we make a new arwen release and `make arwen` is fixed on MacOs also

**Comment by yuriygeorge** [comment] 2020-06-21 18:37
I noticed that this line in config/functions.cfg, MacOs does not have a /lib/ directory, and not possible to create one:

mkdir: /lib: Read-only file system

`sudo cp -f $GOPATH/pkg/mod/github.com/\!elrond\!network/arwen-wasm-vm@$ARWEN_VERSION/wasmer/libwasmer_linux_$ARWEN_ARCH.so /lib/`

So, I change the above so the .so library is copied over to /usr/local/lib/.

But now, how do I tell Elrond to look at that /usr/local/lib/libwasmer_linux_amd64.so

**Comment by yuriygeorge** [comment] 2020-06-21 18:49
https://ide.elrond.com/travis-builds/ARWEN_v0.3.15-120-g03d0b3f_darwin_amd64.tar.gz

I downloaded that library, and I have libwasmer_darwin_amd64.dylib

where am I supposed to put that file? Or how do I tell node to look for that new location instead of the old:

`/Users/ccorcov/Projects/elrond/wasmer/target/release/deps/libwasmer_runtime_c_api.dylib`

(And why in the world is ccorcov hardcode :DDDD)

**Comment by yuriygeorge** [comment] 2020-06-21 18:51
<img width="813" alt="Screen Shot 2020-06-21 at 1 51 08 PM" src="https://user-images.githubusercontent.com/4934760/85232660-432adb00-b3c6-11ea-8135-be2f8c18766a.png">
I was able to get this far, by setting LD_LIBRARY_PATH, and also renaming the libwasmer_darwin_amd64.dylib to libwasmer_runtime_c_api.dylib to match

**Comment by yuriygeorge** [comment] 2020-06-21 19:06
Nice turns out the necessary .dylib was already compiled! I found it here and copied it to my lib folder. (Then used export LD_LIBRARY_PATH= to show where to find .dylib)

cp ~/go/pkg/mod/github.com/\!elrond\!network/arwen-wasm-vm@v0.3.19/wasmer/libwasmer_darwin_amd64.dylib /usr/local/lib/libwasmer_runtime_c_api.dylib

**Comment by yuriygeorge** [comment] 2020-06-21 21:04
Ok, so even though I got the nodes running on the Mac. I HIGHLY DOn't recommend it. As the Mac build must have some serious performance issues. When running on the same machine via a Linux VM, the performance is much better.

**Comment by ccorcoveanu** [comment] 2020-12-07 12:30
Newer releases already have updated wasmer builds so the installation should work now without extra manual steps. But as @yuriygeorge suggests, I would also not recommend running a validator on a personal mac except for developing purposes.

**Closed** 2020-12-07 12:36 UTC
Labels: bug

**Comment by Dentrax** [comment] 2021-12-07 17:55
Getting same error on commit 65dc6cdb045c295812160feb74fd43f1a6adcd15:
```bash
$ ./node
dyld: Library not loaded: @executable_path/libwasmer_darwin_amd64.dylib
  Referenced from: /Users/furkan/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/./node
  Reason: image not found
[1]

$ make arwen
Building the Arwen binary has been deprecated.
```

Go: 1.17.2
OS: macOS 11

I got confused on this issue. Can someone please clarify and give full instruction step for the macOS on the README? Should I install external dependency or project? If so, how and where? Thanks!

@predam @yuriygeorge

**Comment by Dentrax** [comment] 2021-12-07 18:02
It seems the following one worked for me:
```
$ cp ~/go/pkg/mod/github.com/\!elrond\!network/arwen-wasm-vm@v1.4.22/wasmer/libwasmer_darwin_amd64.dylib /usr/local/lib
```
