### ISSUE TITLE
Wrong observer shard id in termui

### ISSUE THREAD

**Issue by ahakla** [ElrondNetwork/elrond-go#786] opened 2019-12-10 19:56 UTC
Hi dear devs!
Just a small thing: I started nodes as observers in different shards, using the `-destination-shard-as-observer` option. However, the node's termui says Shard 0, whereas the explorer does show the correct shard.

**Comment by bogdan-rosianu** [comment] 2019-12-11 10:11
Hello !
You mean that in `explorer -> validators` the shards are displayed correctly ? 

Thanks

**Comment by bogdan-rosianu** [comment] 2019-12-11 12:05
This is strange because the information which is displayed in termui and explorer is fetched from the same place. I will take a look

**Comment by ahakla** [comment] 2019-12-12 01:49
I suspect the termui is getting it's shard id from config/config.toml, where it is set to "0" by default.

**Comment by bogdan-rosianu** [comment] 2019-12-12 09:29
No, the information is taken from a component which knows the shard ID. Can you provide some more details about this issue ? (printscreens, addresses, the session.info file and so on)

**Comment by ahakla** [comment] 2019-12-12 22:14
Hi! I'd stopped and I just restarted the nodes. Now I can't reproduce what I got before. Everything seems consistent now, shard ID in the termui is correct now. So I don't know what happened earlier...

**Comment by ahakla** [comment] 2019-12-12 23:44
Anyway, I saved the session.info file when the termui displayed shard 0:

```
PkBlockSign:2735d1b6fe1a89b1d6eba70cea70d40dc881fede86d236fa368a8bcf28eb727c4030648a7651e6551f578401118084c6f86191b873c3943b730ab760c0b8a75e52fa88731820004aefa4e88857248333946f50bc7b4e4721dddc1cba7d3ad7d1626aa23eb25b0db1e71236cce57585852982f8cdc704aaee07c9c59385ea3591
PkAccount:48c340827dfcfec5e61926e81a772bc8ba54d137ff2b8703d507cfcf17a58040
ShardId:1
TotalShards:5
AppVersion:v1.0.61-0-ge6dbedbc/go1.13.4/linux-amd64
GenesisTimeStamp:1576080000

Started with parameters:
genesis-file = ./config/genesis.json
nodesSetup-file = ./config/nodesSetup.json
port = 0
config = ./config/config.toml
configEconomics = ./config/economics.toml
configPreferences = ./config/prefs.toml
p2pconfig = ./config/p2p.toml
gasCostsConfig = ./config/gasSchedule.toml
profile-mode = false
tx-sign-sk-index = 0
sk-index = 0
num-of-nodes = 18446744073709551615
storage-cleanup = false
initialBalancesSkPemFile = ./config/initialBalancesSk.pem
initialNodesSkPemFile = ./config/initialNodesSk.pem
gops-enable = false
serversconfig = ./config/server.toml
rest-api-interface = localhost:8082
rest-api-debug = false
disable-ansi-color = false
logLevel = *:INFO
use-prometheus = false
use-log-view = true
bootstrap-round-index = 18446744073709551615
tx-indexing = true
destination-shard-as-observer = 1
help, h = <nil>
```

In config/config.toml, the setting was:

```
[GeneralSettings]
   # DestinationShardAsObserver represents the desired shard when running as observer
   # value will be given as string. For example: "0", "1", "15", "metachain"
   DestinationShardAsObserver = "0"
```

**Comment by iulianpascalau** [comment] 2019-12-23 08:26
Will close this issue for now as we are unable to reproduce the problem. Re-checked the source code, everything seems ok. Please open a new issue if this thing happens again. Thanks.

**Closed by iulianpascalau** 2019-12-23 08:26 UTC
Labels: needs investigation
