### ISSUE TITLE
[BUG] After creating a Staking Pool out of an existing node no delegation is shown in wallet.

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/elrond-go#3560] opened 2021-11-04 18:20 UTC
After creating a Staking Pool out of an existing validator node I don't see any delegation in the web wallet so I have no way to undelegate again using the web wallet.

## Reproducible steps:

- Stake a node [Transaction](https://testnet-explorer.elrond.com/transactions/59e734fe0d9624ea03f57cf3b3d65da873041670d3d9d652bb4ee66bf31865bb)
- Create a Staking Pool [Transaction](https://testnet-explorer.elrond.com/transactions/3aefdf71b306c2a2cecf339ba27c8f0ceb58e58c7aae06918b77eb3445ec20f9)
- Take a look into the wallet

## What was expected:
Expected to instantly see a delegation of 2500 (or at least 1250) to the Staking Pool that could be undelegated again.

## What actually happened:
No active delegation was found, no possibility to undelegate anything. 
According to Ben ([Telegram History](https://t.me/ElrondValidators/183236)), this can be resolved by interacting with the contract or waiting for an epoch change.

**Comment by gabi-vuls** [comment] 2021-11-05 11:22
Hello MWFIAE,
Thank you for your feedback. 

When you create a staking pool there are few more details that you might be aware of:
-  the first thing you did was to stake a node -> you are now a validator
- the second one was to create a staking pool. -> doing this  you as a validator became staking provider by creating a new delegation contract -> in this delegation contract (yours) users can delegate egld. And here (from their perspective) they should see data in my total delegation in wallet.  But from your perspective you are the owner of that delegation contract. 

If you want to manipulate and see more easy what is happening inside your contract we encourage you to use the delegation dashboard tool that can be found [here](https://github.com/ElrondNetwork/starter-dapp/tree/master/react-delegationdashboard)

Thank you !

**Comment by MWFIAE** [comment] 2021-11-05 11:43
Hi @gabi-vuls !

But I can also delegate to my own staking pool though. (At least that was possible from the web wallet too).

I also see that the delegation dashboard regards the node stake (and the 2 extra egld I staked via web wallet) as delegation.
However I have no possibility to undelegate that amount from the web wallet again.

I also should only be required to stake the minimum of 1250 egld as the owner, the rest should be considered a normal delegation in my opinion.

**Comment by gabi-vuls** [comment] 2021-11-05 12:15
Hello @MWFIAE 

The issue is reported and we will come with a fix as soon as possible. 
Thank you for the detailed feedback.

**Comment by gabi-vuls** [comment] 2021-12-06 11:34
The issue is fixed now :D

**Closed by gabi-vuls** 2021-12-06 11:34 UTC
Labels: bug
